---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/auth/login":
    post:
      summary: login auth
      responses:
        '200':
          description: successful
  "/documents/{type}":
    parameters:
    - name: type
      in: path
      description: type
      required: true
      schema:
        type: string
    get:
      summary: show document
      responses:
        '200':
          description: successful
    post:
      summary: create document
      responses:
        '200':
          description: successful
    put:
      summary: update document
      responses:
        '200':
          description: successful
    delete:
      summary: delete document
      responses:
        '200':
          description: successful
  "/organization":
    get:
      summary: show organization
      responses:
        '200':
          description: successful
    post:
      summary: create organization
      responses:
        '200':
          description: successful
    put:
      summary: update organization
      responses:
        '200':
          description: successful
    delete:
      summary: delete organization
      responses:
        '200':
          description: successful
  "/templates/{type}":
    parameters:
    - name: type
      in: path
      description: type
      required: true
      schema:
        type: string
    get:
      summary: show template
      responses:
        '200':
          description: successful
  "/users":
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/me":
    get:
      summary: me user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
